#다이어리 프로젝트
CREATE TABLE DIARY (
	DIARY_NUM INT PRIMARY KEY AUTO_INCREMENT
	, DIARY_DATE DATETIME UNIQUE DEFAULT SYSDATE()
	, FEELING VARCHAR(20)
	, TITLE VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(5000) NOT NULL
);

SELECT * FROM diary;